server:
  port: 8089
#  servlet:
#    context-path: /demo

spring:
  datasource:
    url: jdbc:hive2://172.16.1.128:10000/default
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    username:
    password:
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 5
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 60000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20